service: circuitbreaker-gcp
frameworkVersion: ">=1.65.0"
provider:
  name: google
  runtime: nodejs10.x
  memorySize: 128
  project: develop-circuitbreaker-ch-com
  credentials: ~/.gcloud/develop-circuitbreaker-ch-com-6ebc07f29eab.json

plugins:
  - serverless-google-cloudfunctions

functions:
  circuitbreakerCloudFunction:
    handler: index.handler
    timeout: 3
    environment:
      CIRCUITBREAKER_TABLE:
        Ref: circuits
    events:
      - httpApi:
          method: GET
          path: /circuitbreakerCloud
          
package:
  exclude:
    - ./client/**
    - .vscode
    - .serverless
